### ISSUE TITLE
Problems with saving and resuming a game.

### ISSUE THREAD

**Issue by mboom** [mboom/TI2206#55]
The saved board will be used after the first mouse click of the user. The saved board should be used when loading the game.

**Comment by mboom** [comment]
This problem is caused by a fault in the update board mechanisms, which is solved. But after the code restructure the save and resume methods should be updated.

**Comment by jannelie** [comment]
Save and resume aren't working properly, the singleton variables make problems when saving these object. This needs to be fixed.

**Comment by jannelie** [comment]
We choose to save only the score.
You will get a new board. Because the board is always random filled, it is hard to save.
Also this will give an opportunity to cheat, wich is always fun.
