### ISSUE TITLE
problem with FindBugs error: ...  may expose internal representation by ...

### ISSUE THREAD

**Issue by msimidzioski** [mboom/TI2206#76]
Bug: gamelogic.GameGuiMethods.getSelectedCoords() may expose internal representation by returning GameGuiMethods.selectedcoords

**Comment by mboom** [comment]
These kind of bugs appeared a couple of weeks ago, I have still no solution for this. I believe it has a little impact on the quality of the code, but almost nothing on the functionality. I guess, unless someone comes up with a solution, we discuss these bugs Tuesday and decide what to do with it. For now I think we can ignore these bugs.
